name: Broadcast Sample App
author: Vonage, Inc.
website: https://vonage.com
tags:
 - sample
 - broadcast
description: This sample app shows how to use the OpenTok HLS Broadcast functionality in a JavaScript app.
image: https://assets.tokbox.com/img/vonage/Vonage_VideoAPI_black.svg
platforms:
 - js
